# =============================================
# BuildInstaller.ps1 - TigerSqlCmd Installer Builder
# Author: IT Tiger
# =============================================

$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$cliProject = Join-Path $projectRoot 'ItTiger.TigerSqlCmd\ItTiger.TigerSqlCmd.csproj'
$versionFile = Join-Path $projectRoot 'Version.props'
$issFile = Join-Path $PSScriptRoot 'Installer.iss'
$workingDir = Join-Path $PSScriptRoot 'WorkingDir'
$cliOutputDir = Join-Path $workingDir 'cli'

[xml]$versionXml = Get-Content -LiteralPath $versionFile
$version = [string]$versionXml.Project.PropertyGroup.Version
if ([string]::IsNullOrWhiteSpace($version)) {
    throw "Could not read Version from $versionFile."
}

$versionParts = @($version.Split('.'))
if ($versionParts.Count -gt 4 -or ($versionParts | Where-Object { $_ -notmatch '^\d+$' })) {
    throw "Version '$version' must contain one to four numeric components for Inno Setup."
}
$versionInfo = (@($versionParts) + @('0', '0', '0', '0'))[0..3] -join '.'
$filenameVersion = $version -replace '\.', '_'

Write-Host "`nBuilding TigerSqlCmd installer v$version..." -ForegroundColor Cyan

if (Test-Path -LiteralPath $workingDir) {
    Remove-Item -LiteralPath $workingDir -Recurse -Force
}
New-Item -ItemType Directory -Path $cliOutputDir -Force | Out-Null

Write-Host "Publishing tiger-sqlcmd to $cliOutputDir..."
dotnet publish $cliProject -c Release -o $cliOutputDir
if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE."
}

$runtimeConfigFile = Join-Path $cliOutputDir 'tiger-sqlcmd.runtimeconfig.json'
$runtimeOptions = (Get-Content -LiteralPath $runtimeConfigFile -Raw | ConvertFrom-Json).runtimeOptions
$frameworks = @($runtimeOptions.framework) + @($runtimeOptions.frameworks) | Where-Object { $_ }
if (@($frameworks).Count -ne 1 -or $frameworks[0].name -ne 'Microsoft.NETCore.App') {
    $found = ($frameworks | ForEach-Object { "$($_.name) $($_.version)" }) -join ', '
    throw "Expected one Microsoft.NETCore.App reference in $runtimeConfigFile; found: $found."
}

$runtimeName = $frameworks[0].name
$runtimeVersion = $frameworks[0].version
$runtimeMajorMinor = ($runtimeVersion -split '\.')[0..1] -join '.'
Write-Host "Required runtime: $runtimeName $runtimeVersion (x64)"

$generatedDefines = @"
; Generated by BuildInstaller.ps1 from Version.props and tiger-sqlcmd.runtimeconfig.json.
#define ProductVersion "$version"
#define ProductVersionInfo "$versionInfo"
#define SetupBaseFilename "TigerSqlCmdSetup_${filenameVersion}_x64"
#define DotNetFrameworkName "$runtimeName"
#define DotNetRuntimeVersion "$runtimeVersion"
#define DotNetRuntimeMajorMinor "$runtimeMajorMinor"
"@
Set-Content -LiteralPath (Join-Path $workingDir 'BuildDefines.iss') -Value $generatedDefines
Set-Content -LiteralPath (Join-Path $workingDir 'VERSION.txt') -Value $version

Write-Host 'Resolving Inno Setup Compiler (ISCC.exe)...'
$innoKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 7_is1'
$innoPath = (Get-ItemProperty -Path $innoKey -ErrorAction SilentlyContinue).InstallLocation
if (-not $innoPath -or -not (Test-Path -LiteralPath (Join-Path $innoPath 'ISCC.exe'))) {
    throw 'Inno Setup Compiler (ISCC.exe) not found. Install Inno Setup 7.'
}

$innoSetupExe = Join-Path $innoPath 'ISCC.exe'
Write-Host 'Compiling installer with ISCC...'
& $innoSetupExe $issFile
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed with exit code $LASTEXITCODE."
}

$installerPath = Join-Path $PSScriptRoot "Output\TigerSqlCmdSetup_${filenameVersion}_x64.exe"
if (-not (Test-Path -LiteralPath $installerPath)) {
    throw "Expected installer was not produced: $installerPath"
}
Write-Host "`nTigerSqlCmd installer built successfully: $installerPath" -ForegroundColor Green
