[CmdletBinding()]
param(
    [string] $ExpectedVersion,
    [string] $OutputDirectory,
    [switch] $NoBuild
)

$ErrorActionPreference = "Stop"

$projectRoot  = Split-Path -Parent $PSScriptRoot
$cliProject   = Join-Path $projectRoot 'ItTiger.TigerSqlCmd\ItTiger.TigerSqlCmd.csproj'
$versionFile  = Join-Path $projectRoot 'Version.props'
$issFile      = Join-Path $PSScriptRoot 'Installer.iss'
$workingDir   = Join-Path $PSScriptRoot 'WorkingDir'
$cliOutputDir = Join-Path $workingDir 'cli'

[xml]$versionXml = Get-Content -LiteralPath $versionFile
$version = [string]$versionXml.Project.PropertyGroup.Version
if ([string]::IsNullOrWhiteSpace($version)) {
    throw "Could not read Version from $versionFile."
}
if (-not [string]::IsNullOrWhiteSpace($ExpectedVersion) -and $version -cne $ExpectedVersion) {
    throw "Version.props version '$version' does not match expected version '$ExpectedVersion'."
}

$versionParts = @($version.Split('.'))
if ($versionParts.Count -gt 4 -or ($versionParts | Where-Object { $_ -notmatch '^\d+$' })) {
    throw "Version '$version' must contain one to four numeric components for Inno Setup."
}
$versionInfo = (@($versionParts) + @('0', '0', '0', '0'))[0..3] -join '.'

Write-Host "`nBuilding TigerSqlCmd installer v$version..." -ForegroundColor Cyan

# Clean the ignored staging directory, then publish the CLI into the same subfolder
# layout used by TigerWrap.
Write-Host 'Cleaning WorkingDir...'
if (Test-Path -LiteralPath $workingDir) {
    Get-ChildItem -LiteralPath $workingDir -Force | Remove-Item -Recurse -Force
}
New-Item -ItemType Directory -Path $cliOutputDir -Force | Out-Null

Write-Host "Publishing tiger-sqlcmd to $cliOutputDir..."
$publishArguments = @('publish', $cliProject, '-c', 'Release', '-o', $cliOutputDir)
if ($NoBuild) {
    $publishArguments += @('--no-build', '--no-restore')
}
& dotnet @publishArguments
if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE."
}

$runtimeConfigFile = Join-Path $cliOutputDir 'tiger-sqlcmd.runtimeconfig.json'
$runtimeOptions = (Get-Content -LiteralPath $runtimeConfigFile -Raw | ConvertFrom-Json).runtimeOptions
$frameworks = @($runtimeOptions.framework) + @($runtimeOptions.frameworks) | Where-Object { $_ }
if (@($frameworks).Count -ne 1 -or $frameworks[0].name -ne 'Microsoft.NETCore.App') {
    $found = ($frameworks | ForEach-Object { "$($_.name) $($_.version)" }) -join ', '
    throw "Expected a single Microsoft.NETCore.App framework reference in $runtimeConfigFile; found: $found. The installer prerequisite check only handles the base .NET runtime."
}

$runtimeName = $frameworks[0].name
$runtimeVersion = $frameworks[0].version
$runtimeMajorMinor = ($runtimeVersion -split '\.')[0..1] -join '.'
Write-Host "Required runtime: $runtimeName $runtimeVersion (x64)"

$dotnetDefines = @"
; Auto-generated by BuildInstaller.ps1 from tiger-sqlcmd.runtimeconfig.json - do not edit.
#define DotNetFrameworkName "$runtimeName"
#define DotNetRuntimeVersion "$runtimeVersion"
#define DotNetRuntimeMajorMinor "$runtimeMajorMinor"
"@
Set-Content -LiteralPath (Join-Path $workingDir 'DotNetRuntime.iss') -Value $dotnetDefines
Set-Content -LiteralPath (Join-Path $workingDir 'VERSION.txt') -Value $version

$releaseDefines = @"
; Auto-generated by BuildInstaller.ps1 from Version.props - do not edit.
#define TigerSqlCmdVersion "$version"
#define TigerSqlCmdVersionInfo "$versionInfo"
#define TigerSqlCmdOutputBaseFilename "TigerSqlCmdSetup_$($version -replace '\.', '_')"
"@
Set-Content -LiteralPath (Join-Path $workingDir 'ReleaseMetadata.iss') `
    -Value $releaseDefines -Encoding utf8NoBOM

Write-Host 'Resolving Inno Setup Compiler (ISCC.exe)...'
$innoKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Inno Setup 7_is1'
$innoPath = (Get-ItemProperty -Path $innoKey -ErrorAction SilentlyContinue).InstallLocation
if (-not $innoPath -or -not (Test-Path -LiteralPath (Join-Path $innoPath 'ISCC.exe'))) {
    throw 'Inno Setup Compiler (ISCC.exe) not found. Install Inno Setup 7.'
}

$innoSetupExe = Join-Path $innoPath 'ISCC.exe'
$installerPath = Join-Path $PSScriptRoot "Output\TigerSqlCmdSetup_$($version -replace '\.', '_').exe"
if (Test-Path -LiteralPath $installerPath) {
    Remove-Item -LiteralPath $installerPath -Force
}
Write-Host 'Compiling installer with ISCC...'
& $innoSetupExe $issFile
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed with exit code $LASTEXITCODE."
}

if (-not (Test-Path -LiteralPath $installerPath)) {
    throw "Expected installer was not produced: $installerPath"
}
if (-not [string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $resolvedOutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
    New-Item -ItemType Directory -Path $resolvedOutputDirectory -Force | Out-Null
    $destinationPath = Join-Path $resolvedOutputDirectory ([IO.Path]::GetFileName($installerPath))
    Copy-Item -LiteralPath $installerPath -Destination $destinationPath -Force
    $installerPath = $destinationPath
}
Write-Host "`nTigerSqlCmd installer built successfully: $installerPath" -ForegroundColor Green
