; ============================================
; TigerSqlCmd Installer Script
; Version:     0.8.4
; InstallType: Machine-wide (admin required)
; Author:      IT Tiger
; ============================================

; Required .NET runtime, derived from the published CLI's runtimeconfig.json.
; Generated by BuildInstaller.ps1 - run it (or "dotnet build
; ItTiger.TigerSqlCmd.Installer -c Release") before compiling this script directly.
#ifnexist "WorkingDir\DotNetRuntime.iss"
  #error "WorkingDir\DotNetRuntime.iss is missing - run BuildInstaller.ps1 to generate it"
#endif
#include "WorkingDir\DotNetRuntime.iss"

#include "environment.iss"
#include "dotnet.iss"

[Setup]
; Stable installer identity used for upgrades and by package managers. It must never change.
AppId=ItTiger.TigerSqlCmd
AppName=TigerSqlCmd
AppVersion=0.8.4
DefaultDirName={autopf}\ItTiger\TigerSqlCmd
DefaultGroupName=TigerSqlCmd
OutputBaseFilename=TigerSqlCmdSetup_0_8_4
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
DisableProgramGroupPage=yes
VersionInfoDescription=TigerSqlCmd installer
VersionInfoVersion=0.8.4.0
UninstallDisplayIcon={app}\cli\tiger-sqlcmd.exe
AlwaysShowDirOnReadyPage=yes

; Publisher and URLs
AppPublisher=IT Tiger
AppPublisherURL=https://www.ittiger.net/
AppSupportURL=https://www.ittiger.net/projects/tigerquery/
AppUpdatesURL=https://github.com/rkozlowski/TigerQuery/releases

ChangesEnvironment=yes

[Files]
; Install CLI output into a subfolder, matching the TigerWrap layout.
Source: "WorkingDir\cli\*"; DestDir: "{app}\cli"; Flags: recursesubdirs

; Include VERSION.txt in the product root.
Source: "WorkingDir\VERSION.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\TigerSqlCmd"; Filename: "{cmd}"; Parameters: "/K ""{app}\cli\tiger-sqlcmd.exe"" --help"; WorkingDir: "{app}\cli"

[Code]
var
  DotNetInstallRequested: Boolean;

function CmdLineParamExists(const Value: string): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
    if CompareText(ParamStr(I), Value) = 0 then
    begin
      Result := True;
      exit;
    end;
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
  DotNetInstallRequested := False;
  if IsRequiredDotNetInstalled() then
    exit;

  if WizardSilent() then
  begin
    { No interactive prompts in silent mode: install the runtime only when
      explicitly requested via /INSTALLDOTNET, otherwise fail with a clear
      prerequisite error (Setup exits with a nonzero exit code). }
    if CmdLineParamExists('/INSTALLDOTNET') then
    begin
      DotNetInstallRequested := True;
      exit;
    end;
    Log('Prerequisite missing: Microsoft .NET {#DotNetRuntimeMajorMinor} Runtime (x64). '
      + 'Rerun with /INSTALLDOTNET to download and install it, or install it first.');
    SuppressibleMsgBox(
      'TigerSqlCmd requires the Microsoft .NET {#DotNetRuntimeMajorMinor} Runtime (x64), which is not installed.'#13#10#13#10
      + 'Install it from https://dotnet.microsoft.com/download/dotnet/{#DotNetRuntimeMajorMinor}'#13#10
      + 'or rerun Setup with the /INSTALLDOTNET option.',
      mbCriticalError, MB_OK, IDOK);
    Result := False;
    exit;
  end;

  case TaskDialogMsgBox('.NET Runtime required',
         'TigerSqlCmd requires the Microsoft .NET {#DotNetRuntimeMajorMinor} Runtime (x64).'#13#10#13#10
         + 'The required runtime is not installed. Would you like TigerSqlCmd Setup to '
         + 'download and install it now?'#13#10#13#10
         + 'The runtime is downloaded directly from Microsoft.',
         mbConfirmation, MB_YESNO, ['&Download and install', '&Cancel setup'], 0) of
    IDYES: DotNetInstallRequested := True;
  else
    Result := False;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  if DotNetInstallRequested then
    Result := InstallRequiredDotNet();
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    EnvAddPath(ExpandConstant('{app}\cli'));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    EnvRemovePath(ExpandConstant('{app}\cli'));
end;
